language: objective-c

osx_image: xcode8.1
xcode_workspace: SampleProject.xcworkspace
xcode_scheme: SampleProject
xcode_sdk: iphonesimulator9.3

script:
- xcodebuild clean -project SampleProject.xcodeproj -scheme SampleProject -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' build test | xcpretty -c --test --color
