language: objective-c

osx_image: xcode8.1
xcode_workspace: SampleProject.xcworkspace
xcode_scheme: SampleProject
xcode_sdk: iphonesimulator9.3

script:
- xcodebuild clean build test -project SampleProject.xcodeproj -scheme SampleProject
