language: objective-c

script:
  - xctool -sdk iphonesimulator -workspace SampleProject.xcworkspace -scheme SampleProject build test

osx_image: xcode8.1
xcode_workspace: SampleProject.xcworkspace
xcode_scheme: SampleProject
xcode_sdk: iphonesimulator10.1
